In [69]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [70]:
cancer = load_breast_cancer()

X = pd.DataFrame(cancer.data, columns=cancer.feature_names)
y = pd.Series(cancer.target, name="target")

In [71]:
X.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [72]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [73]:
X.describe()

       mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In [74]:
val_size = 0.2      # train_size = 1 - 0.2 - 0.125 = 0.675
test_size = 0.125
random_state = 42
is_shuffle = True

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=val_size,
    shuffle=is_shuffle,
    random_state=random_state
)
# tach X -> X_train, X_val
# X_train -> X_train, X_test
X_train, X_test, y_train, y_test = train_test_split(
    X_train, y_train,
    test_size=test_size,
    shuffle=is_shuffle,
    random_state=random_state
)
print(f"Training set size: {len(X_train)}")
print(f"Validation set size: {len(X_val)}")
print(f"Test set size: {len(X_test)}")

Training set size: 398
Validation set size: 114
Test set size: 57

# Data preprocessing

In [75]:
scaler = StandardScaler()
# Tinh lai mean va chuan hoa lai tu X_train (nguy, do lech chuan)
X_train_scaled = scaler.fit_transform(X_train)

# transform = su dung mean vaa ... phia tren
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print("First row of training data before and after scaling:")
for col, before, after in zip(X_train.columns, X_train.iloc[0], X_train_scaled[0]):
    print(f"{col:12s}: {before:8.4f} → {after:8.4f}")

First row of training data before and after scaling:
mean radius :  19.5500 →   1.5751
mean texture:  23.2100 →   0.9668
mean perimeter: 128.9000 →   1.5606
mean area   : 1174.0000 →   1.4990
mean smoothness:   0.1010 →   0.3540
mean compactness:   0.1318 →   0.5460
mean concavity:   0.1856 →   1.2428
mean concave points:   0.1021 →   1.4316
mean symmetry:   0.1989 →   0.6036
mean fractal dimension:   0.0588 →  -0.5457
radius error:   0.6107 →   0.7217
texture error:   2.8360 →   2.9758
perimeter error:   5.3830 →   1.1876
area error  :  70.1000 →   0.6163
smoothness error:   0.0112 →   1.3511
compactness error:   0.0410 →   0.8235
concavity error:   0.0747 →   1.2804
concave points error:   0.0344 →   3.5143
symmetry error:   0.0277 →   0.8261
fractal dimension error:   0.0062 →   0.8522
worst radius:  20.8200 →   0.9799
worst texture:  30.4400 →   0.8282
worst perimeter: 142.0000 →   1.0698
worst area  : 1313.0000 →   0.7874
worst smoothness:   0.1251 →  -0.2841
worst compactness:   0.2414 →  -0.0632
worst concavity:   0.3829 →   0.5388
worst concave points:   0.1825 →   1.0562
worst symmetry:   0.2576 →  -0.5315
worst fractal dimension:   0.0760 →  -0.4328

# KNN classifier implementation

In [76]:
k = 5
knn_classifier = KNeighborsClassifier(n_neighbors=k)
knn_classifier.fit(X_train_scaled, y_train)

KNeighborsClassifier()

# Evaluate the Model

In [77]:
y_pred = knn_classifier.predict(X_val_scaled)

accuracy = accuracy_score(y_val, y_pred)
print(f"Accuracy {accuracy:.4f}")


print("\nClassification Report:")
print(classification_report(y_val, y_pred, target_names=cancer.target_names))

Accuracy 0.9474

Classification Report:
              precision    recall  f1-score   support

   malignant       0.93      0.93      0.93        43
      benign       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

Make prediction on test set

In [78]:
y_pred = knn_classifier.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=cancer.target_names))

Accuracy 1.0000

Classification Report:
              precision    recall  f1-score   support

   malignant       1.00      1.00      1.00        23
      benign       1.00      1.00      1.00        34

    accuracy                           1.00        57
   macro avg       1.00      1.00      1.00        57
weighted avg       1.00      1.00      1.00        57